RDMA/uverbs: Update for semantic conflict with drm-misc
/tmp/next/build/drivers/infiniband/core/ib_core_uverbs.c: In function 'rdma_user_mmap_entry_remove':
/tmp/next/build/drivers/infiniband/core/ib_core_uverbs.c:249:17: error: implicit declaration of function 'dma_buf_move_notify' [-Wimplicit-function-declaration]
  249 |                 dma_buf_move_notify(uverbs_dmabuf->dmabuf);
      |                 ^~~~~~~~~~~~~~~~~~~

Signed-off-by: Mark Brown <broonie@kernel.org>
Reviewed-by: Christian König <christian.koenig@amd.com>
Signed-off-by: Christian König <christian.koenig@amd.com>
Link: https://lore.kernel.org/r/aZyhDuaF5vi05KBY@sirena.org.uk
(cherry picked from commit 61c0f69a2ff79c8f388a9e973abb4853be467127)
Signed-off-by: Kelsey Steele <kelseys@nvidia.com>